
import puzzlesJson from "./eimisweeper-puzzles.json"
import spritesJson from "./eimisweeper-sprites.json"

export const sprites: Record<string, string> = spritesJson;

export type EimisweeperSettings = {
  chording: boolean,
  flagging: boolean,
};

export type Pos = {
  x: number,
  y: number,
};

export type Cell = {
  pos: Pos,  /* used to position/display the cell */
  adj: number[], /* index into game.cells[] */
  content: number | string, /* content when revealed. emote names replaced by images */
  isBomb: boolean,
  isOpen: boolean, // Internal optimization: the cell has no adjacent mines, and is not unknown (?)
  hidden: boolean,
  flagged: boolean,
};

export type BoardGeometry = 'square' | 'hex' | 'cross';

/// Implementation detail. convert from Pos(x,y)->cells[idx]
export type PosIndex = Record<number, Record<number, number>>

// Information to specify a particular minesweeper board
export type BoardInfo = {
  geometry: BoardGeometry,
  x: number,
  y: number,
  totalMines: number,
  showTotalMines: boolean,
  totalQs?: number,
  showTotalQs?: boolean,
  noGuessing: boolean,
}

// Information about which cells are mines/hidden/unknown etc
export type SerializedBoardData = {
  content: string,
  visible: string,
}

// A unique puzzle created by a person
export type EimisweeperPuzzleData = {
  title: string,
  author: string,
  date: string,
  display?: Record<string,string>, // override things to display a certain way, eg emotes/images
  info: BoardInfo,
  data: SerializedBoardData,
};
type UncheckedPuzzle = {
  title: string,
  author: string,
  date: string,
  display?: Record<string,string>, // override things to display a certain way, eg emotes/images
  info: {
    geometry?: BoardGeometry,
    x: number,
    y: number,
    totalMines?: number,
    showTotalMines?: boolean,
    totalQs?: number,
    showTotalQs?: boolean,
    noGuessing?: boolean,
  },
  data: SerializedBoardData,
};

// Add defaults
function setPuzzleDefaults(puzzle: UncheckedPuzzle): EimisweeperPuzzleData {
  return {...puzzle,
    info: {
      geometry: 'square',
      totalMines: (puzzle.data.content.match(/\*/g)||[]).length,
      showTotalMines: true,
      totalQs: (puzzle.data.content.match(/[^0-9* \n]/g)||[]).length,
      showTotalQs: false,
      noGuessing: true,
      ...puzzle.info
    }
  }
}
export const puzzles: EimisweeperPuzzleData[] = (puzzlesJson as UncheckedPuzzle[]).map(setPuzzleDefaults);

/// Information to display an in-progress game in the browser
export type LiveBoard = {
  cells: Cell[],
  index: PosIndex,
  info: BoardInfo,
}
export type EimisweeperGame = {
  title?: string,
  author?: string,
  date?: string,
  board: LiveBoard,
  minesPlaced: boolean, // currently unused, should always be true
  generator: EimisweeperRandomBoardgen | EimisweeperPuzzleData,
};

export type EimisweeperRandomBoardgen = BoardInfo
//{
//  info: BoardInfo,
//  randomSeed?: number, /* if unset, a random one is used */
//  startingPos?: number, /* if it was generated by clicking on this square */
//};

//type EimisweeperBoardgen = EimisweeperPuzzleData | EimisweeperRandomBoardgen;


/// range(3) => [0,1,2]
export function range(x: number): number[] {
  return Array.from({length: x}, (_, i) => i);
}
const randrange = (n: number) => Math.floor(Math.random()*n);

/// Export the current game (serialize but do not encode/compress)
export function serializeBoard(game: EimisweeperGame): SerializedBoardData|null {
  if (!game.minesPlaced) return null;
  const board = game.board;
  const content = range(board.info.y).map(
    y => range(board.info.x).map(
      x => (y in board.index) && (x in board.index[y]) ? board.cells[board.index[y][x]].content : ' '
    ).join('')
  ).join('\n');
  const visible = range(board.info.y).map(
    y => range(board.info.x).map(
      x => (y in board.index) && (x in board.index[y]) ? board.cells[board.index[y][x]].hidden?'H':'V' : ' '
    ).join('')
  ).join('\n');
  return {
    content: content,
    visible: visible,
  };
}

/// recreate the board for a game if it has changed
/// mainly for the index and adjacency list while using the editor
export function recreateBoard(board: LiveBoard): LiveBoard {
  // rebuild the ordering
  const sorted_cells = [...board.cells].sort((a,b) => (a.pos.y-b.pos.y)===0 ? a.pos.x-b.pos.x : a.pos.y-b.pos.y)
  const cell_positions = sorted_cells.map(c=>c.pos);
  // rebuild the position index
  const index = buildIndex(cell_positions);
  // rebuild the adjacency graph
  const adjacent = buildAdjacency(cell_positions, index, board.info.geometry);
  // update the adjacency for all cells
  return {
    cells: sorted_cells.map((cell, i) => ({...cell, adj: adjacent[i]})),
    index: index,
    info: board.info,
  };
}

/// Convert a serialized puzzle board into a live game state
export function generatePuzzle(gen: EimisweeperPuzzleData): EimisweeperGame {
  const cell_positions: Pos[] = [];
  let x: number = 0;
  let y: number = 0;
  const content: string = gen.data.content;
  const visible: string = gen.data.visible;
  if (content.length !== visible.length) throw new Error("invalid puzzle data");
  const cell_content: string[] = [];
  const cell_visible: boolean[] = [];
  let ci = 0;
  for (const c of content) {
    const v: string = visible[ci];
    if (((c==='\n')!==(v==='\n')) || ((c===' ')!==(v===' '))) {
      throw new Error("invalid puzzle data");
    }
    if (c==='\n') {
      x = 0;
      y++;
    } else {
      if (c!=' ') { // don't create a cell for spaces; position is empty
        cell_positions.push({x: x, y: y});
	cell_content.push(c);
	cell_visible.push(v==="V");
      }
      x++;
    }
    ci++;
  }
  const index = buildIndex(cell_positions);
  const adjacent = buildAdjacency(cell_positions, index, gen.info.geometry);
  const cells: Cell[] = [];
  let idx = 0;
  for (const pos of cell_positions) {
    let content: string | number = gen.display && (cell_content[idx] in gen.display) ? gen.display[cell_content[idx]] : cell_content[idx];
    if (0 <= +content && +content <= 9) {
      content = +content;
    }
    cells.push({
      pos: pos,
      adj: adjacent[idx],
      content: content,
      isBomb: cell_content[idx]==='*',
      isOpen: cell_content[idx]==='0',
      hidden: !cell_visible[idx],
      flagged: false,
    });
    idx++;
  }
  return {
    board: {
      cells: cells,
      index: index,
      info: gen.info,
    },
    title: gen.title,
    author: gen.author,
    date: gen.date,
    minesPlaced: true,
    generator: gen,
  };
}

/// Build the index from (x,y)->cell index
export function buildIndex(cells: Pos[]): PosIndex {
  const index: PosIndex = {};
  let cell_idx = 0;
  for (const pos of cells) {
    // add to index
    if (index[pos.y] === undefined) index[pos.y]={};
    index[pos.y][pos.x] = cell_idx;
    cell_idx++;
  }
  return index;
}

/// Build the cell adjacency graph (cell idx -> [cell idx])
export function buildAdjacency(cells: Pos[], index: PosIndex, geom: BoardGeometry): number[][] {
  const adjacent: number[][] = [];
  for (const pos of cells) {
    const adj: number[] = [];
    const x = pos.x;
    const y = pos.y;
    for (const dy of [-1, 0, 1]) for (const dx of [-1,0,1])
      if ((dy!=0 || dx!=0) && (y+dy) in index && (x+dx) in index[y+dy])
        if (geom==='hex'? dy===0 || (y%2===0 ? dx <= 0 : dx >= 0) :
            geom==='cross'? (dx===0 || dy===0) :
            true)
        adj.push(index[y+dy][x+dx]);
    adjacent.push(adj);
  }
  return adjacent;
}

/// Return a list of mine placements (as [cell idx])
export function placeMines(info: BoardInfo, cells: number, safestart: number[]=[]): number[] {
  // place mines randomly with uniform distribution
  // TODO further documentation for [board.generator.startingPos]
  // and whether cells are already revealed here
  // TODO place mines respecting NoGuessing
  const mine_indices: number[] = [];
  // TODO
  //if (game.generator.startingPos !== undefined) {
  //  const start: Pos = game.generator.startingPos
  //  const start_idx: number = game.board.index[start.y][start.x];
  //  safestart = [start_idx, ...game.board.cells[start_idx].adj];
  //}
  const safe = range(cells); // remaining non-mine positions
  const minesToPlace = Math.min(cells - safestart.length, info.totalMines);
  for (let mines=0; mines < minesToPlace; mines++) {
    // choose a random non-mine position
    let idx: number = randrange(safe.length);
    let iters: number = 0;
    while (iters < 100 && safestart.includes(safe[idx])) {
      // can't put a mine in the starting region (if any)
      idx = randrange(safe.length);
      iters++;
    }
    if (iters == 100) break;
    // move the chosen position from non-mines to mines
    mine_indices.push(...safe.splice(idx, 1));
  }
  return mine_indices;
}

/// Generate a board from random settings
export function generateRandomBoard(info: EimisweeperRandomBoardgen): EimisweeperGame {
  if (info.geometry !== 'square') {
    throw new Error('only square games currently supported for random generation');
  }
  if (info.noGuessing === true) {
    throw new Error('no-guess random games not supported yet');
  }
  //if (gen.randomSeed === undefined) {
  //  // TODO: implement this? e.g. for Daily
  //  gen.randomSeed = Math.random();
  //}
  // generate cell positions
  const cell_positions: Pos[] = [];
  for (let y=0; y < info.y; y++) {
    for (let x=0; x < info.x; x++) {
      // positions can be included/excluded based on geometry
      cell_positions.push({x: x, y: y,});
    }
  }
  const index = buildIndex(cell_positions);
  // calculate cell adjacency according to geometry and build real list
  const adjacent: number[][] = buildAdjacency(cell_positions, index, info.geometry);
  // place mines (TODO: currently no safe zone; you can instantly lose
  const mine_idxs: number[] = placeMines(info, cell_positions.length);
  const cells = cell_positions.map((pos, idx) => {
    const isBomb = mine_idxs.includes(idx);
    const adjMines = adjacent[idx].filter(i2 => mine_idxs.includes(i2)).length;
    return {
      pos: pos,
      adj: adjacent[idx],
      content: isBomb ? "*" : adjMines,
      isBomb: isBomb,
      isOpen: !isBomb && adjMines===0,
      hidden: true,
      flagged: false,
    };
  });
  // place unknowns after calculating mine counts
  // since we want to place them where they matter (and not on top of mines)
  const q_idxs: number[] = placeQs(cells, info.totalQs || 0);
  return {
    board: {
      cells: cells.map((cell, idx) => q_idxs.includes(idx)?{...cell, content: "?", isOpen: false}:cell),
      index: index,
      info: info,
    },
    minesPlaced: true,
    generator: info,
  };
}

function placeQs(cells: Cell[], n: number): number[] {
  const valid: number[] = cells.filter(cell=>
      !cell.isBomb && (
        !cell.isOpen || // nonzero, or: zero but blocks opening of some cell
        cell.adj.some(a=>[...new Set(cells[a].adj).intersection(new Set(cell.adj))]
                          .every(b=>!cells[b].isOpen))
      )
  ).map(cell=>cells.indexOf(cell));
  const qs: number[] = [];
  for (let q=0; q < n && valid.length; q++) {
    // choose a random non-mine position
    let idx: number = randrange(valid.length);
    // move the chosen position from safe/normal visibility to qs
    qs.push(...valid.splice(idx, 1));
  }
  return qs;
}

