
import puzzlesJson from "./eimisweeper-puzzles.json"
import spritesJson from "./eimisweeper-sprites.json"

export const sprites: Dictionary<string, string> = spritesJson;

/* global settings / controls */
export const EimisweeperSettings = {
  allowFlagging: true,
  allowChording: false,
};

type Pos = {
  x: number,
  y: number,
};

type Cell = {
  pos: Pos,  /* used to position/display the cell */
  adjacent: number[], /* index into game.cells[] */
  content: string, /* content when revealed. emote names replaced by images */
  isBomb: boolean,
  isOpen: boolean, // Internal optimization: the cell has no adjacent mines, and is not unknown (?)
  hidden: boolean,
  flagged: boolean,
};

type BoardGeometry = 'square' | 'hex';

/// Implementation detail. convert from Pos(x,y)->cells[idx]
type PosIndex = Dictionary<number, Dictionary<number, number>>

// Information to specify a particular minesweeper board
type BoardInfo = {
  geometry: BoardGeometry,
  x: number,
  y: number,
  totalMines: number,
  showTotalMines: boolean,
  totalQs: number,
  showTotalQs: boolean,
  noGuessing: boolean,
}

// Information about which cells are mines/hidden/unknown etc
type SerializedBoardData = {
  content: string,
  visible: string,
}

// A unique puzzle created by a person
type EimisweeperPuzzleData = {
  title: string,
  author: string,
  date: string,
  //puzzleID: string,
  display?: Dictionary<string,string>, // override things to display a certain way, eg emotes/images
  info: BoardInfo,
  data: SerializedBoardData,
};

// Add defaults
export const puzzles: EimisweeperPuzzleData[] = puzzlesJson.map(
  puzzle => {
    if (puzzle.info.geometry===undefined) puzzle.info.geometry='square';
    if (puzzle.info.totalMines===undefined) puzzle.info.totalMines=(puzzle.data.content.match(/\*/g)||[]).length;
    if (puzzle.info.showTotalMines===undefined) puzzle.info.showTotalMines=true;
    if (puzzle.info.totalQs===undefined) puzzle.info.totalQs=(puzzle.data.content.match(/[^0-9* \n]/g)||[]).length;
    if (puzzle.info.showTotalQs===undefined) puzzle.info.showTotalQs=false;
    if (puzzle.info.noGuessing===undefined) puzzle.info.noGuessing=true;
    //if (puzzle.puzzleID===undefined) puzzle.puzzleID='';
    return puzzle;
  }
) as EimisweeperPuzzleData[];

/// Information to display an in-progress game in the browser
type LiveBoard = {
  cells: Cell[],
  index: PosIndex,
  info: BoardInfo,
}
type EimisweeperGame = {
  title?: string,
  author?: string,
  date?: string,
  board: LiveBoard,
  minesPlaced: boolean, // this can be false for randomly-generated games (they are placed on first click)
  generator: EimisweeperRandomBoardgen | EimisweeperPuzzleData,
};

type EimisweeperRandomBoardgen = {
  info: BoardInfo,
  randomSeed?: number, /* if unset, a random one is used */
  startingPos?: number, /* if it was generated by clicking on this square */
};

type EimisweeperBoardgen = EimisweeperPuzzleData | EimisweeperRandomBoardgen;


/// range(3) => [0,1,2]
export function range(x: number): number[] {
  return Array.from({length: x}, (_, i) => i);
}

/// Export the current game (serialize but do not encode/compress)
export function serializeBoard(game: EimisweeperGame): SerializedBoardData {
  if (!game.minesPlaced) return;
  const board = game.board;
  const content = range(board.info.y).map(
    y => range(board.info.x).map(
      x => (y in board.index) && (x in board.index[y]) ? board.cells[board.index[y][x]].content : ' '
    ).join('')
  ).join('\n');
  const visible = range(board.info.y).map(
    y => range(board.info.x).map(
      x => (y in board.index) && (x in board.index[y]) ? board.cells[board.index[y][x]].hidden?'H':'V' : ' '
    ).join('')
  ).join('\n');
  return {
    content: content,
    visible: visible,
  };
}

/// recreate the board for a game if it has changed
/// mainly for the index and adjacency list while using the editor
export function recreateBoard(board: LiveBoard): LiveBoard {
  // rebuild the ordering
  const sorted_cells = [...board.cells].sort((a,b) => (a.pos.y-b.pos.y)===0 ? a.pos.x-b.pos.x : a.pos.y-b.pos.y)
  const cell_positions = sorted_cells.map(c=>c.pos);
  // rebuild the position index
  const index = buildIndex(cell_positions);
  // rebuild the adjacency graph
  const adjacent = buildAdjacency(cell_positions, index, board.info.geometry);
  // update the adjacency for all cells
  return {
    cells: sorted_cells.map((cell, i) => ({...cell, adj: adjacent[i]})),
    index: index,
    info: board.info,
  };
}

/// Convert a serialized puzzle board into a live game state
export function generatePuzzle(gen: EimisweeperPuzzleData): EimisweeperGame {
  let cell_positions: Pos[] = [];
  let x: number = 0;
  let y: number = 0;
  const content: string = gen.data.content;
  const visible: string = gen.data.visible;
  if (content.length !== visible.length) return undefined; // TODO throw error for bad data
  let cell_content: string[] = [];
  let cell_visible: boolean[] = [];
  for (const [ci, c] of Object.entries(content)) {
    const v: string = visible[ci];
    if (((c==='\n')!==(v==='\n')) || ((c===' ')!==(v===' '))) {
      // TODO: throw error for bad data
      return undefined;
    }
    if (c==='\n') {
      x = 0;
      y++;
    } else {
      if (c!=' ') { // don't create a cell for spaces; position is empty
        cell_positions.push({x: x, y: y});
	cell_content.push(c);
	cell_visible.push(v==="V");
      }
      x++;
    }
  }
  const index = buildIndex(cell_positions);
  const adjacent = buildAdjacency(cell_positions, index, gen.info.geometry);
  let cells: Cell[] = [];
  for (const [idx, pos] of Object.entries(cell_positions)) {
    let content = gen.display && (cell_content[idx] in gen.display) ? gen.display[cell_content[idx]] : cell_content[idx];
    if (0 <= +content && +content <= 9) {
      content = +content;
    }
    cells.push({
      pos: pos,
      adj: adjacent[idx],
      content: content,
      isBomb: cell_content[idx]==='*',
      isOpen: cell_content[idx]==='0',
      hidden: !cell_visible[idx],
      flagged: false,
    });
  }
  return {
    board: {
      cells: cells,
      index: index,
      info: gen.info,
    },
    title: gen.title,
    author: gen.author,
    date: gen.date,
    minesPlaced: true,
    generator: gen,
  };
}

/// Build the index from (x,y)->cell index
export function buildIndex(cells: Pos[]): PosIndex {
  let index: PosIndex = {};
  let cell_idx = 0;
  for (const pos of cells) {
    // add to index
    if (index[pos.y] === undefined) index[pos.y]={};
    index[pos.y][pos.x] = cell_idx;
    cell_idx++;
  }
  return index;
}

/// Build the cell adjacency graph (cell idx -> [cell idx])
export function buildAdjacency(cells: Pos[], index: PosIndex, geom: BoardGeometry): number[][] {
  let adjacent: number[][] = [];
  for (const [cell_idx, pos] of Object.entries(cells)) {
    let adj: number[] = [];
    const x = pos.x;
    const y = pos.y;
    for (const dy of [-1, 0, 1]) for (const dx of [-1,0,1])
      if ((dy!=0 || dx!=0) && (y+dy) in index && (x+dx) in index[y+dy])
        adj.push(index[y+dy][x+dx]);
    adjacent.push(adj);
  }
  return adjacent;
}

/// Return a list of mine placements (as [cell idx])
export function placeMines(board: EimisweeperGame): number[] {
  // place mines randomly with uniform distribution
  // TODO further documentation for [board.generator.startingPos]
  // and whether cells are already revealed here
  // TODO place mines respecting NoGuessing
  let mine_indices: number[] = [];
  let start_adj: number[] = [];
  if (board.generator.startingPos !== undefined) {
    const start: Pos = board.generator.startingPos
    const start_idx: number = board.index[start.y][start.x];
    start_adj = board.cells[start_idx].adjacent;
  }
  for (let mines=0; mines < gen.totalMines; mines++) { 
    let idx: number = Random() % cell_positions.length; // TODO
    let iters: number = 0;
    while (iters < 100 && (
      mine_indices.includes(idx) // can't put two mines on same tile
      || start_adj.includes(idx))) { // or a mine next to the starting tile, if any
      idx = Random() % cell_positions.length; // TODO
      iters++;
    }
    if (iters == 100) break;
  }
  return mine_indices;
}

/// Generate a board from random settings
export function generateBoard(gen: EimisweeperRandomBoardgen): EimisweeperGame {
  if (gen.info.geometry !== 'square') {
    alert('Error: only square games currently supported for random generation');
    return undefined;
  }
  if (gen.info.noGuessing === true) {
    alert('Error: no-guess random games not supported yet');
    return undefined;
  }
  if (gen.randomSeed === undefined) {
    // TODO: implement this? e.g. for Daily
    gen.randomSeed = Random();
  }
  // generate cell positions
  let cell_positions: Pos[] = [];
  for (let y=0; y < gen.info.y; y++) {
    for (let x=0; x < gen.info.x; x++) {
      // positions can be included/excluded based on geometry
      cell_positions.push({x: x, y: y,});
    }
  }
  const index = buildIndex(cell_positions);
  // calculate cell adjacency according to geometry and build real list
  const adj: number[][] = buildAdjacency(cell_positions, index, gen.geometry);
  let cells: Cell[] = [];
  for (const [idx, pos] of Object.entries(cell_positions)) {
    cells.push({
      pos: pos,
      adjacent: adj[idx],
      content: "", // mines have not been placed yet
      isBomb: false,
      isOpen: true,
      hidden: true,
      flagged: false,
    });
  }
  return {
    board: {
      cells: cells,
      index: index,
    },
    info: gen.info,
    minesPlaced: false,
    generator: gen,
  };
}


